language: r
r:
  - release
cache: packages
# https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
dist: trusty
sudo: false

branches:
  only:
    - src

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: src
  target_branch: master
