language: r
r:
  - release
cache: packages
# https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
dist: trusty
sudo: false

branches:
  only:
    - master

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: travis-blogdown.yihui.name
