# Adapted from https://github.com/jimhester/azuretest

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'rocker/r-ver:latest'

steps:
- script: |
    echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
    echo '.libPaths("~/Rlibs")' >> ~/.Rprofile
    mkdir -p ~/Rlibs
  displayName: 'Installing R'
- task: CacheBeta@0
  inputs:
    key: "blogown 0.14"
    path: "~/Rlibs"
  displayName: 'Caching Packages'
- script: |
    R -e "install.packages(c('blogdown'))"
  displayName: 'Installing packages'
#- script: |
#    Rscript -e 'blogdown::build_site(local = FALSE, method = c("html", "custom"), run_hugo = FALSE)'
#  displayName: 'Build site'