# Adapted from https://github.com/jimhester/azuretest

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'rocker/r-ver:latest'

variables:
  R_LIBS_USER: '$(Build.SourcesDirectory)/rlib'

steps:
- script: |
    echo 'The value of R_LIBS_USER is ${R_LIBS_USER}'
    echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
    echo '.libPaths("${R_LIBS_USER}")' >> ~/.Rprofile
    mkdir -p "${R_LIBS_USER}"
  displayName: 'Set up R'
- task: CacheBeta@0
  inputs:
    key: DESCRIPTION
    path: $(R_LIBS_USER)
  displayName: 'Caching Packages'
- script: |
    R -e "install.packages(c('blogdown'))"
  displayName: 'Installing packages'
#- script: |
#    Rscript -e 'blogdown::build_site(local = FALSE, method = c("html", "custom"), run_hugo = FALSE)'
#  displayName: 'Build site'