# Adapted from https://github.com/jimhester/azuretest

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'rocker/r-ver:latest'

variables:
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'

steps:
- script: |
    echo "Creating directory for R packages ==> ${R_LIBS_USER}"
    mkdir -p "${R_LIBS_USER}"
    echo "Updating ~/.Rprofile"
    echo "options(repos = 'https://cloud.r-project.org')" > ~/.Rprofile
    echo ".libPaths('${R_LIBS_USER}')" >> ~/.Rprofile
    echo "The content of ~/.Rprofile is now ==>"
    sed -e 's/^/>> /' ~/.Rprofile
  displayName: 'Set up R'
- script: |
    echo "Installing packrat"
    R -e "install.packages(c('packrat'))"
    # R -e "install.packages(c('packrat'), lib = '${R_LIBS_USER}')"
  displayName: 'Install packrat'
- task: CacheBeta@0
  inputs:
    key: |
      packrat
      $(Agent.OS)
      $(Build.SourcesDirectory)/packrat/packrat.lock
    path: $(Build.SourcesDirectory)/packrat
  displayName: 'Caching packages'
- script: |
    cd $(Build.SourcesDirectory)
    R -e "packrat::restore(restart = FALSE)"
  displayName: 'Restore packages'
#- script: |
#    Rscript -e 'blogdown::build_site(local = FALSE, method = c("html", "custom"), run_hugo = FALSE)'
#  displayName: 'Build site'