# Adapted from https://github.com/jimhester/azuretest

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'rocker/r-ver:latest'

variables:
  R_INSTALL_DIR: ~/rlib

steps:
- script: |
    echo "The value of R_INSTALL_DIR is ${R_INSTALL_DIR}"
    echo "options(repos = \"https://cloud.r-project.org\")" > ~/.Rprofile
    echo ".libPaths(\"${R_INSTALL_DIR}\")" >> ~/.Rprofile
    mkdir -p "${R_INSTALL_DIR}"
    cat ~/.Rprofile
  displayName: 'Set up R'
- task: CacheBeta@0
  inputs:
    key: DESCRIPTION
    path: $(R_INSTALL_DIR)
  displayName: 'Caching Packages'
- script: |
    R -e "install.packages(c('blogdown'))"
  displayName: 'Installing packages'
#- script: |
#    Rscript -e 'blogdown::build_site(local = FALSE, method = c("html", "custom"), run_hugo = FALSE)'
#  displayName: 'Build site'