# Adapted from https://github.com/jimhester/azuretest

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  containerImage: rstudio/r-base:3.6-xenial
  container: $[ variables['containerImage'] ]

variables:
  CI: true
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'

steps:
- script: |
    echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
    mkdir -p ${R_LIBS_USER}
    sudo apt-get update && sudo apt-get install -y libxml2-dev libssl-dev
  displayName: 'Installing R'
- script: |
    R -e "install.packages(c('blogdown'))"
  displayName: 'Install package dependencies'
#- script: |
#    Rscript -e 'blogdown::build_site(local = FALSE, method = c("html", "custom"), run_hugo = FALSE)'
#  displayName: 'Build site'