---
title: "Hello World!"
author: "Curtis Alexander"
date: "2017-09-28"
slug: hello-world
categories: []
tags: ["r", "python", "sas", "shell", "racket"]
---

`Hello World!` **+** `Hello World! x 5`

### R
```{r, eval = FALSE, echo = TRUE}
writeLines("Hello World!")


for (i in rep("Hello World!", 5)) {
  writeLines(i)
}


library(purrr)
rep("Hello World!", 5) %>%
  walk(writeLines)
```

### Python
```{r, engine = 'python', eval = FALSE, echo = TRUE}
# Python 3
print("Hello World!")


for i in range(5):
    print("Hello World!")

    
from toolz import pipe
pipe("Hello World!\n", lambda i: i * 5, print)
```

### SAS
```{r, engine = 'sas', eval = FALSE, echo = TRUE}
data _null_;
  file stdout ;
  put "Hello World!";
run;


data _null_;
  file stdout ;
  do i = 1 to 5;
    put "Hello World!";
  end;
run;
```

### Bash
```{r, engine = 'bash', eval = FALSE, echo = TRUE}
echo "Hello World!"


for i in {1..5} do
    echo "Hello World!"
done
```

### Awk
```{r, engine = 'bash', eval = FALSE, echo = TRUE}
awk 'BEGIN { print "Hello World!" }'


awk 'BEGIN { for (i=0; i<=5; i++) print "Hello World!" }'
```

### Racket
```racket
#lang racket
(print "Hello World!")


(for-each (lambda (i)
            (printf "Hello World!\n"))
          (stream->list (in-range 5)))
```
