---
title: PyOxidizer
author: Curtis Alexander
date: "2019-08-09"
slug: pyoxidizer
categories: []
tags: ["python"]
draft: true
---

I have been keeping an eye on a new project - [PyOxidizer]() - that looks quite promising to distribute Python applications/scripts as a single executable by embedding Python.  This post will not repeat much of what the author, [Gregory Szorc](https://github.com/indygreg), has already noted about the motivations, technical achievments, etc.  Specifically, Gregory has a detailed and informative (as well as enjoyable) [post](https://gregoryszorc.com/blog/2019/06/24/building-standalone-python-applications-with-pyoxidizer/) announcing PyOxidizer.  I appreciate that within the introduction Gregory notes the concerns regarding the lack of easy distribution of Python applications to non-developers!

>Aside: I quite enjoy working in and utilizing Python. But I consider the difficulty in distributing code as a real drawback for Python.  This is part of the reason I continue to side-eye [F#](https://fsharp.org/) and to a lesser degree [C#](https://docs.microsoft.com/en-us/dotnet/csharp/).  With [.Net Core](https://docs.microsoft.com/en-us/dotnet/core/), the languages that run on .Net have a story for [application deployment](https://docs.microsoft.com/en-us/dotnet/core/).  Currently, there are three potential deployment models, all built into the CLI tooling, with one such model being a [self-contained deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#self-contained-deployment) that includes the .Net Core runtime.  Taking this a step further will be the Ahead of Time compilation Microsoft is working on for [.Net 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/#fast-startup-low-footprint-and-lower-memory-usage).  With .Net 5 aiming to be a unified platform for distributing apps to most any target desired, it looks to me to be a compelling platform to potentially build upon.

Thus, this post will describe how one can utilize PyOxidizer for a single, simple use case - taking a single Python script (a single `.py` file) and distributing it as an executable.

### Code for this post

All code for this post can be found in the following repos:

<repo 1>
<repo 2>

In addition to the repos, all the steps below are encapsulated in a single shell script that one can use as a form of shorthand.

### Multiple Repositories

Before going through the steps to create an executable, I should note my preferred way to organize (at this point in time).

First, my preference is to maintain the Python script that PyOxidizer will consume in its own repository.  This allows me to first develop the script, ensuring it is documented and working before adding the compilation overhead.  It also allows the script to be used by someone who has Python on their system and doesn't need to consume a binary.

After creating the inital repository with my Python script, I then create a second repository (named the same as the Python script with the postfix `cli`) that will be use PyOxidizer to produce a binary.  This second repository consumes the first as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).


### Get PyOxidizer

First, get PyOxidizer.  Simple enough - just follow the instructions [here](https://pyoxidizer.readthedocs.io/en/latest/getting_started.html) to [install Rust](https://pyoxidizer.readthedocs.io/en/latest/getting_started.html#installing-rust) and then [install PyOxidizer](https://pyoxidizer.readthedocs.io/en/latest/getting_started.html#installing-pyoxidizer).


### Initialize a project
