---
title: "Colophon"
author: "Curtis Alexander"
date: "2019-07729"
---

### Website 

This website was built with the following technologies.

* [blogdown](https://bookdown.org/yihui/blogdown/)
* [Hugo](https://gohugo.io/)

### Theme

The [Hugo theme](https://themes.gohugo.io/) in use is [cocoa enhanced](https://themes.gohugo.io/cocoa-eh-hugo-theme/).

I made one slight change to the theme in order to better space the image logo against headers.  Within `themes/cocoa-eh-hugo-theme/layouts/partials/css/main.css`, I make the following update.

```css
div.header .container .logo {
  max-width: 100px;
  margin-left: -2em;
  /* Added to better space image logo against headers */
  padding-right: 5px;
}
```

Ultimately, as noted within [Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/), I manage [my theme](https://github.com/curtisalexander/cocoa-eh-hugo-theme) through a [git submodule](https://bookdown.org/yihui/blogdown/version-control.html).

### Building and Hosting

Building is performed with [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/).  My specific project is public and may be viewed at the [Azure DevOps site](https://dev.azure.com/curtisalexander/calex.org).

Hosting is provided through [netlify](https://www.netlify.com/).

Simple instructions for getting setup can be found within [Chapter 3.1](https://bookdown.org/yihui/blogdown/netlify.html) of the [blogdown](https://bookdown.org/yihui/blogdown/) book/site.

A more complex set of instructions may be found at <strike>[this blog post](blog/github-travis-netlify/)</strike> [this blog post](blog/github-azure-netlify/).
